/* prop_net — AP+STA WiFi via the C6, with NVS-stored STA credentials. */
#include "prop_net.h"
#include "prop_engine.h"
#include "prop_settings.h"
#include <string.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_mac.h"
#include "mdns.h"

#define NET_TAG "PROP_NET"
#define MAX_RETRY 8

/* Build-time WiFi secret: wifi_secret.h is generated by main/CMakeLists.txt from the
 * gitignored wifi_secret.env. Guarded so the firmware still builds if it's absent. */
#if defined(__has_include)
#  if __has_include("wifi_secret.h")
#    include "wifi_secret.h"
#  endif
#endif
#ifndef PROP_WIFI_SSID
#define PROP_WIFI_SSID ""
#endif
#ifndef PROP_WIFI_PASS
#define PROP_WIFI_PASS ""
#endif

/* Compile-time fallback STA creds (from wifi_secret.env), used only if none are
 * stored in NVS yet — e.g. a fresh flash or after erase. NVS creds always win. */
#define DEFAULT_STA_SSID    PROP_WIFI_SSID
#define DEFAULT_STA_PASSWD  PROP_WIFI_PASS

static esp_netif_t *s_netif_ap;
static esp_netif_t *s_netif_sta;
static int s_retry_num;
static char s_ip[16] = "0.0.0.0";
static volatile prop_sta_state_t s_sta_state = STA_IDLE;
static volatile int s_rssi;      /* cached signal strength (dBm), 0 = unknown */
static prop_uplink_t s_uplink;   /* cached connected-AP dossier (filled by rssi_task) */
static bool s_ap_up;             /* true once the fallback hotspot is running */
static void rssi_task(void *arg);
static esp_err_t enable_ap(void);

/* How long after boot to wait for the STA to join a known network before falling
 * back to our own hotspot. While STA is connecting the radio isn't also beaconing
 * an AP, which frees co-processor radio time for the join (and for BLE/scans). */
#define AP_FALLBACK_DELAY_MS 60000

static void load_sta_credentials(char *ssid, size_t ssid_len, char *pass, size_t pass_len)
{
    prop_settings_get_str("sta_ssid", ssid, ssid_len, DEFAULT_STA_SSID);
    prop_settings_get_str("sta_pass", pass, pass_len, DEFAULT_STA_PASSWD);
}

static esp_err_t apply_sta_config(const char *ssid, const char *pass)
{
    wifi_config_t sta = {
        .sta = {
            .scan_method = WIFI_ALL_CHANNEL_SCAN,
            .failure_retry_cnt = MAX_RETRY,
            .threshold.authmode = WIFI_AUTH_OPEN,  /* accept open..WPA3 */
            .sae_pwe_h2e = WPA3_SAE_PWE_BOTH,
        },
    };
    strlcpy((char *)sta.sta.ssid, ssid, sizeof(sta.sta.ssid));
    strlcpy((char *)sta.sta.password, pass, sizeof(sta.sta.password));
    return esp_wifi_set_config(WIFI_IF_STA, &sta);
}

static void wifi_event_handler(void *arg, esp_event_base_t base, int32_t id, void *data)
{
    if (base == WIFI_EVENT && id == WIFI_EVENT_STA_START) {
        esp_wifi_connect();
    } else if (base == WIFI_EVENT && id == WIFI_EVENT_STA_DISCONNECTED) {
        strlcpy(s_ip, "0.0.0.0", sizeof(s_ip));
        if (s_retry_num < MAX_RETRY) {
            s_retry_num++;
            esp_wifi_connect();
            ESP_LOGI(NET_TAG, "STA retry %d", s_retry_num);
        } else {
            s_sta_state = STA_FAILED;
            ESP_LOGW(NET_TAG, "STA connect failed");
            /* Out of STA retries and the deferred-hotspot timer may not have fired
             * yet — bring the AP up now so the unit stays reachable for setup. */
            if (!s_ap_up) {
                enable_ap();
            }
        }
        /* Reflect the link the unit actually has: the hotspot only if it's running. */
        prop_engine_set_link(s_ap_up ? LINK_AP : LINK_DOWN);
    } else if (base == IP_EVENT && id == IP_EVENT_STA_GOT_IP) {
        ip_event_got_ip_t *event = (ip_event_got_ip_t *)data;
        esp_ip4addr_ntoa(&event->ip_info.ip, s_ip, sizeof(s_ip));
        ESP_LOGI(NET_TAG, "STA got IP: %s", s_ip);
        s_retry_num = 0;
        s_sta_state = STA_CONNECTED;
        prop_engine_set_link(LINK_STA);
    } else if (base == WIFI_EVENT && id == WIFI_EVENT_AP_STACONNECTED) {
        wifi_event_ap_staconnected_t *e = (wifi_event_ap_staconnected_t *)data;
        ESP_LOGI(NET_TAG, "client "MACSTR" joined hotspot", MAC2STR(e->mac));
    }
}

/* Bring up mDNS so the prop answers "<PROP_HOSTNAME>.local" and advertises its
 * web console over _http._tcp. Best-effort: failure here just means you fall back
 * to the raw IP, so we log and carry on rather than aborting WiFi. */
static void start_mdns(void)
{
    esp_err_t err = mdns_init();
    if (err != ESP_OK) {
        ESP_LOGW(NET_TAG, "mdns_init failed: %s (no .local name)", esp_err_to_name(err));
        return;
    }
    mdns_hostname_set(PROP_HOSTNAME);
    mdns_instance_name_set("Communicator Prop");
    mdns_service_add(NULL, "_http", "_tcp", 80, NULL, 0);
    ESP_LOGI(NET_TAG, "mDNS up: http://%s.local/", PROP_HOSTNAME);
}

static esp_err_t wifi_init_softap(void)
{
    s_netif_ap = esp_netif_create_default_wifi_ap();
    esp_netif_set_hostname(s_netif_ap, PROP_HOSTNAME);
    wifi_config_t ap = {
        .ap = {
            .ssid = PROP_AP_SSID,
            .ssid_len = strlen(PROP_AP_SSID),
            .channel = 1,
            .password = PROP_AP_PASSWD,
            .max_connection = 4,
            .authmode = WIFI_AUTH_WPA2_PSK,
            .pmf_cfg = { .required = false },
        },
    };
    if (strlen(PROP_AP_PASSWD) == 0) {
        ap.ap.authmode = WIFI_AUTH_OPEN;
    }
    esp_err_t err = esp_wifi_set_config(WIFI_IF_AP, &ap);
    if (err == ESP_OK) {
        ESP_LOGI(NET_TAG, "hotspot up: SSID=%s", PROP_AP_SSID);
    }
    return err;
}

/* Bring the fallback hotspot online (idempotent). Switches the radio into APSTA
 * and configures the AP. Used both at boot (when there are no STA creds to try)
 * and as the deferred fallback when the STA hasn't joined in time. */
static esp_err_t enable_ap(void)
{
    if (s_ap_up) {
        return ESP_OK;
    }
    esp_err_t err = esp_wifi_set_mode(WIFI_MODE_APSTA);
    if (err != ESP_OK) {
        ESP_LOGE(NET_TAG, "set APSTA mode failed: %s", esp_err_to_name(err));
        return err;
    }
    err = wifi_init_softap();
    if (err != ESP_OK) {
        return err;
    }
    s_ap_up = true;
    if (s_sta_state != STA_CONNECTED) {
        prop_engine_set_link(LINK_AP);
    }
    return err;
}

/* One-shot: give the STA a window to join a known network; only if it hasn't by
 * then do we beacon our own hotspot (saving radio time on the C6 while joining). */
static void ap_fallback_task(void *arg)
{
    (void)arg;
    vTaskDelay(pdMS_TO_TICKS(AP_FALLBACK_DELAY_MS));
    if (s_sta_state == STA_CONNECTED) {
        ESP_LOGI(NET_TAG, "STA connected within window — hotspot stays off (radio freed)");
    } else {
        ESP_LOGW(NET_TAG, "no STA link after %d s — bringing up fallback hotspot",
                 AP_FALLBACK_DELAY_MS / 1000);
        enable_ap();
    }
    vTaskDelete(NULL);
}

esp_err_t prop_net_init(void)
{
    /* NVS is initialized earlier by prop_settings_init(). */
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT, ESP_EVENT_ANY_ID,
                                                        &wifi_event_handler, NULL, NULL));
    ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT, IP_EVENT_STA_GOT_IP,
                                                        &wifi_event_handler, NULL, NULL));

    /* From here on, calls cross the SDIO bus to the ESP32-C6 co-processor. If the
     * C6's esp_hosted slave firmware is missing or version-incompatible, these
     * fail — we log and return an error rather than ESP_ERROR_CHECK-aborting, so
     * the rest of the prop (display/LEDs/buttons/UI) keeps running without WiFi. */
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    esp_err_t err = esp_wifi_init(&cfg);
    if (err != ESP_OK) {
        ESP_LOGE(NET_TAG, "esp_wifi_init failed: %s — ESP32-C6 co-processor not responding "
                 "or its hosted firmware is incompatible. Running without WiFi.",
                 esp_err_to_name(err));
        prop_engine_set_link(LINK_DOWN);
        return err;
    }

    /* Always create the STA netif. The hotspot is deferred: if we have a network to
     * try, start STA-only and only beacon our own AP if STA hasn't joined within the
     * fallback window (frees C6 radio time). With no saved creds there's nothing to
     * join, so bring the AP up immediately for first-time setup. */
    s_netif_sta = esp_netif_create_default_wifi_sta();
    esp_netif_set_hostname(s_netif_sta, PROP_HOSTNAME);   /* DHCP option 12 */
    char ssid[33] = {0}, pass[65] = {0};
    load_sta_credentials(ssid, sizeof(ssid), pass, sizeof(pass));
    bool have_creds = ssid[0] != '\0';

    if ((err = esp_wifi_set_mode(have_creds ? WIFI_MODE_STA : WIFI_MODE_APSTA)) != ESP_OK) {
        ESP_LOGE(NET_TAG, "WiFi mode set failed: %s. Running without WiFi.", esp_err_to_name(err));
        prop_engine_set_link(LINK_DOWN);
        return err;
    }
    apply_sta_config(ssid, pass);   /* STA config is best-effort */
    s_sta_state = have_creds ? STA_CONNECTING : STA_IDLE;

    err = esp_wifi_start();
    if (err != ESP_OK) {
        ESP_LOGE(NET_TAG, "esp_wifi_start failed: %s. Running without WiFi.", esp_err_to_name(err));
        prop_engine_set_link(LINK_DOWN);
        return err;
    }

    if (have_creds) {
        /* STA-only for now; hotspot held back until the fallback timer (or a hard
         * STA failure) decides we need it. */
        prop_engine_set_link(LINK_DOWN);   /* "seeking" until STA gets an IP */
        xTaskCreate(ap_fallback_task, "ap_fallback", 3072, NULL, 3, NULL);
    } else {
        if ((err = enable_ap()) != ESP_OK) {
            ESP_LOGE(NET_TAG, "hotspot bring-up failed: %s. Running without WiFi.",
                     esp_err_to_name(err));
            prop_engine_set_link(LINK_DOWN);
            return err;
        }
    }

    start_mdns();                     /* advertise <PROP_HOSTNAME>.local */
    xTaskCreate(rssi_task, "rssi", 4096, NULL, 3, NULL);   /* background RSSI poll */
    ESP_LOGI(NET_TAG, "WiFi started (sta ssid='%s', mode=%s)", ssid,
             have_creds ? "STA, AP deferred" : "APSTA");
    return ESP_OK;
}

/* ---- Radio identity helpers (vendor OUI, PHY generation) ------------------ */

const char *prop_phy_label(prop_phy_t phy)
{
    switch (phy) {
        case PROP_PHY_11B:  return "802.11b";
        case PROP_PHY_11G:  return "802.11g";
        case PROP_PHY_11N:  return "WiFi 4";
        case PROP_PHY_11AC: return "WiFi 5";
        case PROP_PHY_11AX: return "WiFi 6";
        default:            return "WiFi";
    }
}

static const char *authmode_str(wifi_auth_mode_t a)
{
    switch (a) {
        case WIFI_AUTH_OPEN:          return "OPEN";
        case WIFI_AUTH_WEP:           return "WEP";
        case WIFI_AUTH_WPA_PSK:       return "WPA";
        case WIFI_AUTH_WPA2_PSK:
        case WIFI_AUTH_WPA_WPA2_PSK:  return "WPA2";
        case WIFI_AUTH_WPA3_PSK:
        case WIFI_AUTH_WPA2_WPA3_PSK: return "WPA3";
        case WIFI_AUTH_OWE:           return "OWE";
        default:                      return "ENT";   /* enterprise / other */
    }
}

static prop_phy_t ap_phy(const wifi_ap_record_t *r)
{
    if (r->phy_11ax) return PROP_PHY_11AX;
    if (r->phy_11ac) return PROP_PHY_11AC;
    if (r->phy_11n)  return PROP_PHY_11N;
    if (r->phy_11g)  return PROP_PHY_11G;
    return PROP_PHY_11B;
}

/* Curated OUI -> vendor table. The first 3 bytes of a MAC are the IEEE-assigned
 * Organizationally Unique Identifier. This is a hand-picked subset of common
 * consumer/AP vendors (real assignments) for prop flavour — vendors own many OUIs,
 * so misses are expected and reported as "UNKNOWN OEM". Author-editable; add rows. */
static const struct { uint8_t oui[3]; const char *vendor; } s_ouis[] = {
    { {0x24,0x0A,0xC4}, "ESPRESSIF" }, { {0x7C,0xDF,0xA1}, "ESPRESSIF" },
    { {0x50,0xC7,0xBF}, "TP-LINK"   }, { {0xAC,0x84,0xC6}, "TP-LINK"   },
    { {0x20,0xE5,0x2A}, "NETGEAR"   }, { {0x9C,0x3D,0xCF}, "NETGEAR"   },
    { {0x24,0xA4,0x3C}, "UBIQUITI"  }, { {0x78,0x8A,0x20}, "UBIQUITI"  }, { {0xFC,0xEC,0xDA}, "UBIQUITI" },
    { {0x2C,0x56,0xDC}, "ASUS"      }, { {0x04,0xD9,0xF5}, "ASUS"      },
    { {0x1C,0xBD,0xB9}, "D-LINK"    }, { {0x78,0x54,0x2E}, "D-LINK"    },
    { {0x3C,0x15,0xC2}, "APPLE"     }, { {0xA4,0x83,0xE7}, "APPLE"     }, { {0xDC,0xA9,0x04}, "APPLE" },
    { {0x5C,0x0A,0x5B}, "SAMSUNG"   }, { {0x8C,0x77,0x12}, "SAMSUNG"   },
    { {0x64,0x09,0x80}, "XIAOMI"    }, { {0x50,0x8F,0x4C}, "XIAOMI"    },
    { {0x00,0xE0,0xFC}, "HUAWEI"    }, { {0x48,0x46,0xFB}, "HUAWEI"    },
    { {0x18,0xB4,0x30}, "NEST"      }, { {0x6C,0xAD,0xF8}, "GOOGLE"    },
    { {0x44,0x65,0x0D}, "AMAZON"    }, { {0xFC,0x65,0xDE}, "AMAZON"    },
    { {0x6C,0x3B,0x6B}, "MIKROTIK"  }, { {0x24,0xDE,0xC6}, "ARUBA"     },
    { {0x00,0x25,0x9C}, "CISCO"     }, { {0xC0,0x8A,0xDE}, "RUCKUS"    },
};

const char *prop_net_oui_vendor(const uint8_t mac[6])
{
    if (!mac) {
        return NULL;
    }
    for (size_t i = 0; i < sizeof(s_ouis) / sizeof(s_ouis[0]); i++) {
        if (mac[0] == s_ouis[i].oui[0] && mac[1] == s_ouis[i].oui[1] &&
            mac[2] == s_ouis[i].oui[2]) {
            return s_ouis[i].vendor;
        }
    }
    return NULL;
}

/* Shared blocking active scan: start it, fetch every record into a freshly
 * malloc'd array. Returns the raw record count (>=0) with *recs set (caller
 * frees), or -1 on error (*recs left NULL). WiFi is already up in APSTA mode.
 * Call from a task, never under the LVGL lock. Both public scan entry points
 * (prop_net_scan, prop_net_scan_channels) build on this. */
static int scan_and_fetch(wifi_ap_record_t **recs)
{
    *recs = NULL;
    wifi_scan_config_t scan_cfg = { 0 };   /* all channels, active scan */
    esp_err_t err = esp_wifi_scan_start(&scan_cfg, true);
    if (err != ESP_OK) {
        ESP_LOGW(NET_TAG, "scan start failed: %s", esp_err_to_name(err));
        return -1;
    }
    uint16_t num = 0;
    esp_wifi_scan_get_ap_num(&num);
    if (num == 0) {
        return 0;
    }
    wifi_ap_record_t *r = calloc(num, sizeof(wifi_ap_record_t));
    if (!r) {
        esp_wifi_clear_ap_list();
        return -1;
    }
    esp_wifi_scan_get_ap_records(&num, r);   /* also frees the internal list */
    *recs = r;
    return (int)num;
}

int prop_net_scan(prop_ap_t *out, int max)
{
    if (!out || max <= 0) {
        return -1;
    }
    wifi_ap_record_t *recs = NULL;
    int num = scan_and_fetch(&recs);
    if (num <= 0) {
        return num;   /* -1 error, or 0 networks (nothing to free) */
    }

    /* Records come back sorted by RSSI (strongest first); de-dup by SSID. */
    int count = 0;
    for (int i = 0; i < num && count < max; i++) {
        const char *ssid = (const char *)recs[i].ssid;
        if (ssid[0] == '\0') {
            continue;   /* hidden network */
        }
        bool dup = false;
        for (int j = 0; j < count; j++) {
            if (strcmp(out[j].ssid, ssid) == 0) { dup = true; break; }
        }
        if (dup) {
            continue;
        }
        strlcpy(out[count].ssid, ssid, sizeof(out[count].ssid));
        memcpy(out[count].bssid, recs[i].bssid, 6);
        out[count].rssi = recs[i].rssi;
        out[count].channel = recs[i].primary;
        out[count].phy = ap_phy(&recs[i]);
        strlcpy(out[count].sec, authmode_str(recs[i].authmode), sizeof(out[count].sec));
        out[count].secured = (recs[i].authmode != WIFI_AUTH_OPEN &&
                              recs[i].authmode != WIFI_AUTH_OWE);
        out[count].ftm = recs[i].ftm_responder;
        count++;
    }
    free(recs);
    ESP_LOGI(NET_TAG, "scan found %d AP(s) (%u raw)", count, num);
    return count;
}

int prop_net_scan_channels(uint8_t out[PROP_NET_CHAN_SLOTS])
{
    if (!out) {
        return -1;
    }
    memset(out, 0, PROP_NET_CHAN_SLOTS);

    wifi_ap_record_t *recs = NULL;
    int num = scan_and_fetch(&recs);
    if (num <= 0) {
        return num;   /* -1 error, or 0 networks */
    }

    /* Fold each AP into its primary channel. A channel's bar reflects BOTH its
     * strongest emitter and how crowded it is: height = strongest-signal% plus a
     * small bump per extra AP. This keeps a lightly-used channel visibly shorter
     * than a congested one instead of every occupied channel pegging at full. */
    int strongest[PROP_NET_CHAN_SLOTS] = { 0 };
    int count[PROP_NET_CHAN_SLOTS] = { 0 };
    for (int i = 0; i < num; i++) {
        int ch = recs[i].primary;
        if (ch < 1 || ch >= PROP_NET_CHAN_SLOTS) {
            continue;   /* 2.4 GHz only (channels 1..13) */
        }
        int pct = (recs[i].rssi + 90) * 2;   /* -90 dBm -> 0, -40 dBm -> 100 */
        if (pct < 8)   pct = 8;              /* any contact lifts the bar off the floor */
        if (pct > 100) pct = 100;
        if (pct > strongest[ch]) strongest[ch] = pct;
        count[ch]++;
    }
    free(recs);

    for (int ch = 1; ch < PROP_NET_CHAN_SLOTS; ch++) {
        int v = strongest[ch] + (count[ch] > 1 ? (count[ch] - 1) * 8 : 0);
        out[ch] = v > 100 ? 100 : (uint8_t)v;
    }
    ESP_LOGI(NET_TAG, "channel scan: %d AP(s) across 2.4 GHz", num);
    return num;
}

esp_err_t prop_net_set_sta_credentials(const char *ssid, const char *password, bool remember)
{
    if (!ssid) {
        return ESP_ERR_INVALID_ARG;
    }
    if (remember) {
        esp_err_t err = prop_settings_set_str("sta_ssid", ssid);
        if (err == ESP_OK) {
            err = prop_settings_set_str("sta_pass", password ? password : "");
        }
        if (err != ESP_OK) {
            return err;
        }
    }

    /* Reconnect with the new credentials (persisted or session-only). */
    s_retry_num = 0;
    s_sta_state = STA_CONNECTING;
    esp_wifi_disconnect();
    apply_sta_config(ssid, password ? password : "");
    esp_wifi_connect();
    ESP_LOGI(NET_TAG, "STA credentials set -> '%s' (%s), reconnecting",
             ssid, remember ? "saved" : "session-only");
    return ESP_OK;
}

esp_err_t prop_net_forget(void)
{
    prop_settings_set_str("sta_ssid", "");
    prop_settings_set_str("sta_pass", "");
    s_retry_num = MAX_RETRY;        /* don't auto-retry the cleared network */
    s_sta_state = STA_IDLE;
    esp_wifi_disconnect();
    strlcpy(s_ip, "0.0.0.0", sizeof(s_ip));
    enable_ap();   /* may have been STA-only; ensure the unit stays reachable */
    prop_engine_set_link(LINK_AP);
    ESP_LOGI(NET_TAG, "STA network forgotten");
    return ESP_OK;
}

prop_sta_state_t prop_net_sta_state(void)
{
    return s_sta_state;
}

void prop_net_get_ip(char *out, size_t out_len)
{
    if (out && out_len) {
        strlcpy(out, s_ip, out_len);
    }
}

int prop_net_get_rssi(void)
{
    return s_rssi;   /* cached by rssi_task; cheap, no SDIO round-trip here */
}

void prop_net_get_uplink(prop_uplink_t *out)
{
    if (out) {
        *out = s_uplink;   /* struct copy; benign race for a readout */
    }
}

static const char *phymode_label(wifi_phy_mode_t m)
{
    switch (m) {
        case WIFI_PHY_MODE_LR:   return "LR";
        case WIFI_PHY_MODE_11B:  return "802.11b";
        case WIFI_PHY_MODE_11G:  return "802.11g";
        case WIFI_PHY_MODE_HT20: return "WiFi 4 / HT20";
        case WIFI_PHY_MODE_HT40: return "WiFi 4 / HT40";
        case WIFI_PHY_MODE_HE20: return "WiFi 6 / HE20";
        default:                 return "WiFi";
    }
}

/* Poll the uplink in the background (~1 Hz) so UI code can read RSSI + the AP
 * dossier without crossing the SDIO bus on the render path — doing that under the
 * LVGL lock stalls the panel. One sta_get_ap_info call yields RSSI, BSSID, channel
 * and country together; negotiated_phymode gives the live PHY. */
static void rssi_task(void *arg)
{
    (void)arg;
    for (;;) {
        wifi_ap_record_t ap;
        if (s_sta_state == STA_CONNECTED && esp_wifi_sta_get_ap_info(&ap) == ESP_OK) {
            s_rssi = ap.rssi;
            s_uplink.connected = true;
            strlcpy(s_uplink.ssid, (const char *)ap.ssid, sizeof(s_uplink.ssid));
            memcpy(s_uplink.bssid, ap.bssid, 6);
            s_uplink.rssi = ap.rssi;
            s_uplink.channel = ap.primary;
            s_uplink.country[0] = (ap.country.cc[0] > ' ') ? ap.country.cc[0] : '\0';
            s_uplink.country[1] = (ap.country.cc[1] > ' ') ? ap.country.cc[1] : '\0';
            s_uplink.country[2] = '\0';
            wifi_phy_mode_t pm;
            if (esp_wifi_sta_get_negotiated_phymode(&pm) == ESP_OK) {
                strlcpy(s_uplink.phy, phymode_label(pm), sizeof(s_uplink.phy));
            } else {
                s_uplink.phy[0] = '\0';
            }
        } else {
            s_rssi = 0;
            s_uplink.connected = false;
        }
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
